version: "3.4"

x-app: &x-app
  build:
    context: .
    dockerfile: Dockerfile.dev
  image: rail-app:dev
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - .psqlrc:/root/.psqlrc:ro
  environment:
    - NODE_ENV=development
    - RAILS_ENV=${RAILS_ENV:-development}
    - REDIS_URL=redis://redis:6379/
    - DATABASE_URL=postgres://app:password@postgres:5432
    - BOOTSNAP_CACHE_DIR=/usr/local/bundle/bootsnap
    - WEBPACKER_DEV_SERVER_HOST=webpacker
    - WEB_CONCURRENCY=1
    - HISTFILE=/app/log/.bash_history
    - PSQL_HISTFILE=/app/log/.psql_history
    - EDITOR=vi

services:
  app: &app
    <<: *x-app
    command: irb
    depends_on:
    - postgres
    - redis

  rails:
    <<: *x-app
    command:
      - "bash"
      - "-c"
      - >
        rm -f /app/tmp/pids/server.pid &&
        bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - app

  sidekiq:
    <<: *x-app
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - app

  webpack:
    <<: *x-app
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    ports:
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    ports:
      - 5432

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
