FROM ruby:alpine

ENV LANG C.UTF-8

RUN apk update && \
    apk add --no-cache \
        build-base \
        tzdata \
        nodejs \
        yarn \
        postgresql-dev \
        libxml2-dev \
        libxslt-dev

ENV ENTRYKIT_VERSION 0.4.0

RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && mv entrykit /bin/entrykit \
    && chmod +x /bin/entrykit \
    && entrykit --symlink

RUN mkdir /app
WORKDIR /app

RUN gem install bundler --force
RUN bundle config build.nokogiri --use-system-libraries

ENTRYPOINT [ \
    "prehook", "ruby -v", "--", \
    "prehook", "bundle --version", "--", \
    "prehook", "bundle install -j3 --quiet", "--"]
