defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  database: <%= ENV.fetch("DATABASE_NAME") { File.basename(Rails.root) } %>_dev
  <<: *defaults

test:
  database: <%= ENV.fetch("DATABASE_NAME") { File.basename(Rails.root) } %>_test
  <<: *defaults

production: &deploy
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>

staging: *deploy
